### ISSUE TITLE
Private Helm Repository cannot be reached

### ISSUE THREAD

**Issue by nickperkins** [tarioch/pre-commit-hooks#1]
**Issue** 

If a Helm repository requires authentication to access, the pre-commit hook is unable to access it.

`Error: looks like "https://charts.private.repo.test/" is not a valid chart repository or cannot be reached: failed to fetch https://charts.private.repo.test/index.yaml : 401 Unauthorized`

**Reproduction**

Add `HelmRepository` resource that requires authentication for access. For example:

```
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: myrepo
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://charts.private.repo.test/
  secretRef:
    name: helmrepo-credentials
```
