### ISSUE TITLE
TypeError ("string indices must be integers, not 'str'",)

### ISSUE THREAD

**Issue by varac** [tarioch/pre-commit-hooks#12]
I'm using v0.5.0 of this hook, but I get this error:

    [ERROR] vaultwarden-hr.yaml: TypeError ("string indices must be integers, not 'str'",)

`vaultwarden-hr.yaml`:

```yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  releaseName: vaultwarden
  chartRef:
    kind: OCIRepository
    name: vaultwarden
    namespace: flux-system
  interval: "24h"
```

`vaultwarden-oci-repo.yaml`: 

```yaml
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: vaultwarden
  namespace: flux-system
spec:
  interval: 1h
  url: oci://tccr.io/truecharts/vaultwarden
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  ref:
    semver: "28.3.3"
```
